
const shipmentStatus = {
  pendingProduction: 'Pending Production',
  scheduled: 'Scheduled',
  onItsWay: 'On Its Way',
  delivered: 'Delivered',
  failure: 'Failure',
  cancelled: 'Cancelled',
  invalidAddress: 'Invalid Address',
  returnToSender: 'Return To Sender'
};

const pendingMockup = 'Pending Mockup';
const inProgress = 'In Progress';
const designReady = 'Design Ready';
const changesRequested = 'Changes Requested';
const productionRequest = 'Production Request';
const productionReady = 'Production Ready';
const approved = 'Approved';

const productStatus = {
  pendingMockup,
  inProgress,
  designReady,
  changesRequested,
  productionRequest,
  productionReady,
  approved,
  inactive: 'Inactive'
};

const redactedText = '** redacted **';


const countries = {
  count: 249,
  next: null,
  previous: null,
  results: [
    { id: 1, iso2: 'AF', iso3: 'AFG', other_known_names: null, name: 'Afghanistan', active: true, provinces: [] },
    { id: 2, iso2: 'AX', iso3: 'ALA', other_known_names: null, name: 'Åland Islands', active: true, provinces: [] },
    { id: 3, iso2: 'AL', iso3: 'ALB', other_known_names: null, name: 'Albania', active: true, provinces: [] },
    { id: 4, iso2: 'DZ', iso3: 'DZA', other_known_names: null, name: 'Algeria', active: true, provinces: [] },
    { id: 5, iso2: 'AS', iso3: 'ASM', other_known_names: null, name: 'American Samoa', active: true, provinces: [] },
    { id: 6, iso2: 'AD', iso3: 'AND', other_known_names: null, name: 'Andorra', active: true, provinces: [] },
    { id: 7, iso2: 'AO', iso3: 'AGO', other_known_names: null, name: 'Angola', active: true, provinces: [] },
    { id: 8, iso2: 'AI', iso3: 'AIA', other_known_names: null, name: 'Anguilla', active: true, provinces: [] },
    { id: 9, iso2: 'AQ', iso3: 'ATA', other_known_names: null, name: 'Antarctica', active: true, provinces: [] },
    { id: 10, iso2: 'AG', iso3: 'ATG', other_known_names: null, name: 'Antigua Barbuda', active: true, provinces: [] },
    { id: 11, iso2: 'AR', iso3: 'ARG', other_known_names: null, name: 'Argentina', active: true, provinces: [] },
    { id: 12, iso2: 'AM', iso3: 'ARM', other_known_names: null, name: 'Armenia', active: true, provinces: [] },
    { id: 13, iso2: 'AW', iso3: 'ABW', other_known_names: null, name: 'Aruba', active: true, provinces: [] },
    { id: 14, iso2: 'AU', iso3: 'AUS', other_known_names: null, name: 'Australia', active: true, provinces: [] },
    { id: 15, iso2: 'AT', iso3: 'AUT', other_known_names: null, name: 'Austria', active: true, provinces: [] },
    { id: 16, iso2: 'AZ', iso3: 'AZE', other_known_names: null, name: 'Azerbaijan', active: true, provinces: [] },
    { id: 17, iso2: 'BS', iso3: 'BHS', other_known_names: null, name: 'Bahamas', active: true, provinces: [] },
    { id: 18, iso2: 'BH', iso3: 'BHR', other_known_names: null, name: 'Bahrain', active: true, provinces: [] },
    { id: 19, iso2: 'BD', iso3: 'BGD', other_known_names: null, name: 'Bangladesh', active: true, provinces: [] },
    { id: 20, iso2: 'BB', iso3: 'BRB', other_known_names: null, name: 'Barbados', active: true, provinces: [] },
    { id: 21, iso2: 'BY', iso3: 'BLR', other_known_names: null, name: 'Belarus', active: true, provinces: [] },
    { id: 22, iso2: 'BE', iso3: 'BEL', other_known_names: null, name: 'Belgium', active: true, provinces: [] },
    { id: 23, iso2: 'BZ', iso3: 'BLZ', other_known_names: null, name: 'Belize', active: false, provinces: [] },
    { id: 24, iso2: 'BJ', iso3: 'BEN', other_known_names: null, name: 'Benin', active: true, provinces: [] },
    { id: 25, iso2: 'BM', iso3: 'BMU', other_known_names: null, name: 'Bermuda', active: true, provinces: [] },
    { id: 26, iso2: 'BT', iso3: 'BTN', other_known_names: null, name: 'Bhutan', active: true, provinces: [] },
    { id: 27, iso2: 'BO', iso3: 'BOL', other_known_names: null, name: 'Bolivia', active: true, provinces: [] },
    { id: 28, iso2: 'BQ', iso3: 'BES', other_known_names: null, name: 'Bonaire', active: true, provinces: [] },
    {
      id: 29,
      iso2: 'BA',
      iso3: 'BIH',
      other_known_names: null,
      name: 'Bosnia Herzegovina',
      active: true,
      provinces: []
    },
    { id: 30, iso2: 'BW', iso3: 'BWA', other_known_names: null, name: 'Botswana', active: true, provinces: [] },
    { id: 31, iso2: 'BR', iso3: 'BRA', other_known_names: null, name: 'Brazil', active: true, provinces: [] },
    {
      id: 32,
      iso2: 'IO',
      iso3: 'IOT',
      other_known_names: null,
      name: 'British Indian Ocean Territory',
      active: true,
      provinces: []
    },
    {
      id: 33,
      iso2: 'VG',
      iso3: 'VGB',
      other_known_names: null,
      name: 'British Virgin Islands',
      active: true,
      provinces: []
    },
    {
      id: 34,
      iso2: 'BN',
      iso3: 'BRN',
      other_known_names: null,
      name: 'Brunei Darussalam',
      active: true,
      provinces: []
    },
    { id: 35, iso2: 'BG', iso3: 'BGR', other_known_names: null, name: 'Bulgaria', active: true, provinces: [] },
    { id: 36, iso2: 'BF', iso3: 'BFA', other_known_names: null, name: 'Burkina Faso', active: true, provinces: [] },
    { id: 37, iso2: 'BI', iso3: 'BDI', other_known_names: null, name: 'Burundi', active: true, provinces: [] },
    { id: 38, iso2: 'KH', iso3: 'KHM', other_known_names: null, name: 'Cambodia', active: true, provinces: [] },
    { id: 39, iso2: 'CM', iso3: 'CMR', other_known_names: null, name: 'Cameroon', active: true, provinces: [] },
    {
      id: 40,
      iso2: 'CA',
      iso3: 'CAN',
      other_known_names: null,
      name: 'Canada',
      active: true,
      provinces: [
        { name: 'Alberta', code: 'AB' },
        { name: 'British Columbia', code: 'BC' },
        { name: 'Manitoba', code: 'MB' },
        { name: 'New Brunswick', code: 'NB' },
        { name: 'Newfoundland', code: 'NL' },
        { name: 'Northwest Territories', code: 'NT' },
        { name: 'Nova Scotia', code: 'NS' },
        { name: 'Nunavut', code: 'NU' },
        { name: 'Ontario', code: 'ON' },
        { name: 'Prince Edward Island', code: 'PE' },
        { name: 'Quebec', code: 'QC' },
        { name: 'Saskatchewan', code: 'SK' },
        { name: 'Yukon', code: 'YT' }
      ]
    },
    {
      id: 41,
      iso2: 'CV',
      iso3: 'CPV',
      other_known_names: null,
      name: 'Cape Verde Islands',
      active: true,
      provinces: []
    },
    { id: 42, iso2: 'KY', iso3: 'CYM', other_known_names: null, name: 'Cayman Islands', active: true, provinces: [] },
    {
      id: 43,
      iso2: 'CF',
      iso3: 'CAF',
      other_known_names: null,
      name: 'Central African Republic',
      active: true,
      provinces: []
    },
    { id: 44, iso2: 'TD', iso3: 'TCD', other_known_names: null, name: 'Chad', active: true, provinces: [] },
    { id: 45, iso2: 'CL', iso3: 'CHL', other_known_names: null, name: 'Chile', active: true, provinces: [] },
    { id: 46, iso2: 'CN', iso3: 'CHN', other_known_names: null, name: 'China', active: true, provinces: [] },
    { id: 47, iso2: 'CX', iso3: 'CXR', other_known_names: null, name: 'Christmas Island', active: true, provinces: [] },
    {
      id: 48,
      iso2: 'CC',
      iso3: 'CCK',
      other_known_names: null,
      name: 'Cocos (Keeling) Islands',
      active: true,
      provinces: []
    },
    { id: 49, iso2: 'CO', iso3: 'COL', other_known_names: null, name: 'Colombia', active: true, provinces: [] },
    { id: 50, iso2: 'KM', iso3: 'COM', other_known_names: null, name: 'Comoros', active: true, provinces: [] },
    { id: 51, iso2: 'CG', iso3: 'COD', other_known_names: null, name: 'Congo', active: true, provinces: [] },
    { id: 52, iso2: 'CK', iso3: 'COK', other_known_names: null, name: 'Cook Islands', active: true, provinces: [] },
    { id: 53, iso2: 'CR', iso3: 'CRI', other_known_names: null, name: 'Costa Rica', active: true, provinces: [] },
    { id: 54, iso2: 'HR', iso3: 'HRV', other_known_names: null, name: 'Croatia', active: true, provinces: [] },
    { id: 55, iso2: 'CU', iso3: 'CUB', other_known_names: null, name: 'Cuba', active: false, provinces: [] },
    { id: 56, iso2: 'CW', iso3: 'CUW', other_known_names: null, name: 'Curacao', active: false, provinces: [] },
    { id: 57, iso2: 'CY', iso3: 'CYP', other_known_names: null, name: 'Cyprus', active: true, provinces: [] },
    { id: 58, iso2: 'CZ', iso3: 'CZE', other_known_names: null, name: 'Czech Republic', active: true, provinces: [] },
    { id: 59, iso2: 'DK', iso3: 'DNK', other_known_names: null, name: 'Denmark', active: true, provinces: [] },
    { id: 60, iso2: 'DJ', iso3: 'DGI', other_known_names: null, name: 'Djibouti', active: true, provinces: [] },
    { id: 61, iso2: 'DM', iso3: 'DMA', other_known_names: null, name: 'Dominica', active: true, provinces: [] },
    {
      id: 62,
      iso2: 'DO',
      iso3: 'DOM',
      other_known_names: null,
      name: 'Dominican Republic',
      active: true,
      provinces: []
    },
    { id: 63, iso2: 'EC', iso3: 'ECU', other_known_names: null, name: 'Ecuador', active: true, provinces: [] },
    { id: 64, iso2: 'EG', iso3: 'EGY', other_known_names: null, name: 'Egypt', active: true, provinces: [] },
    { id: 65, iso2: 'SV', iso3: 'SLV', other_known_names: null, name: 'El Salvador', active: true, provinces: [] },
    {
      id: 66,
      iso2: 'GQ',
      iso3: 'GNQ',
      other_known_names: null,
      name: 'Equatorial Guinea',
      active: true,
      provinces: []
    },
    { id: 67, iso2: 'ER', iso3: 'ERI', other_known_names: null, name: 'Eritrea', active: true, provinces: [] },
    { id: 68, iso2: 'EE', iso3: 'EST', other_known_names: null, name: 'Estonia', active: true, provinces: [] },
    { id: 69, iso2: 'ET', iso3: 'ETH', other_known_names: null, name: 'Ethiopia', active: true, provinces: [] },
    { id: 70, iso2: 'FK', iso3: 'FLK', other_known_names: null, name: 'Falkland Islands', active: true, provinces: [] },
    { id: 71, iso2: 'FO', iso3: 'FRO', other_known_names: null, name: 'Faroe Islands', active: true, provinces: [] },
    { id: 72, iso2: 'FJ', iso3: 'FJI', other_known_names: null, name: 'Fiji', active: true, provinces: [] },
    { id: 73, iso2: 'FI', iso3: 'FIN', other_known_names: null, name: 'Finland', active: true, provinces: [] },
    { id: 74, iso2: 'FR', iso3: 'FRA', other_known_names: null, name: 'France', active: true, provinces: [] },
    { id: 75, iso2: 'GF', iso3: 'GUF', other_known_names: null, name: 'French Guiana', active: true, provinces: [] },
    { id: 76, iso2: 'PF', iso3: 'PYF', other_known_names: null, name: 'French Polynesia', active: true, provinces: [] },
    {
      id: 77,
      iso2: 'TF',
      iso3: 'ATF',
      other_known_names: null,
      name: 'French Southern Territories',
      active: true,
      provinces: []
    },
    { id: 78, iso2: 'GA', iso3: 'GAB', other_known_names: null, name: 'Gabon', active: true, provinces: [] },
    { id: 79, iso2: 'GM', iso3: 'GMB', other_known_names: null, name: 'Gambia', active: true, provinces: [] },
    { id: 80, iso2: 'GE', iso3: 'GEO', other_known_names: null, name: 'Georgia', active: true, provinces: [] },
    { id: 81, iso2: 'DE', iso3: 'DEU', other_known_names: null, name: 'Germany', active: true, provinces: [] },
    { id: 82, iso2: 'GH', iso3: 'GHA', other_known_names: null, name: 'Ghana', active: true, provinces: [] },
    { id: 83, iso2: 'GI', iso3: 'GIB', other_known_names: null, name: 'Gibraltar', active: true, provinces: [] },
    { id: 84, iso2: 'GR', iso3: 'GRC', other_known_names: null, name: 'Greece', active: true, provinces: [] },
    { id: 85, iso2: 'GL', iso3: 'GRL', other_known_names: null, name: 'Greenland', active: true, provinces: [] },
    { id: 86, iso2: 'GD', iso3: 'GRD', other_known_names: null, name: 'Grenada', active: true, provinces: [] },
    { id: 87, iso2: 'GP', iso3: 'GLP', other_known_names: null, name: 'Guadeloupe', active: true, provinces: [] },
    { id: 88, iso2: 'GU', iso3: 'GUM', other_known_names: null, name: 'Guam', active: true, provinces: [] },
    { id: 89, iso2: 'GT', iso3: 'GTM', other_known_names: null, name: 'Guatemala', active: true, provinces: [] },
    { id: 90, iso2: 'GG', iso3: 'GGY', other_known_names: null, name: 'Guernsey', active: true, provinces: [] },
    { id: 91, iso2: 'GN', iso3: 'GIN', other_known_names: null, name: 'Guinea', active: true, provinces: [] },
    { id: 92, iso2: 'GW', iso3: 'GNB', other_known_names: null, name: 'Guinea-Bissau', active: true, provinces: [] },
    { id: 93, iso2: 'GY', iso3: 'GUY', other_known_names: null, name: 'Guyana', active: true, provinces: [] },
    { id: 94, iso2: 'HT', iso3: 'HTI', other_known_names: null, name: 'Haiti', active: true, provinces: [] },
    { id: 95, iso2: 'VA', iso3: 'VAT', other_known_names: null, name: 'Holy See', active: true, provinces: [] },
    { id: 96, iso2: 'HN', iso3: 'HND', other_known_names: null, name: 'Honduras', active: true, provinces: [] },
    { id: 97, iso2: 'HK', iso3: 'HKG', other_known_names: null, name: 'Hong Kong', active: true, provinces: [] },
    { id: 98, iso2: 'HU', iso3: 'HUN', other_known_names: null, name: 'Hungary', active: true, provinces: [] },
    { id: 99, iso2: 'IS', iso3: 'ISL', other_known_names: null, name: 'Iceland', active: true, provinces: [] },
    {
      id: 100,
      iso2: 'IN',
      iso3: 'IND',
      other_known_names: null,
      name: 'India',
      active: true,
      provinces: [
        { name: 'Andaman and Nicobar', code: 'AN' },
        { name: 'Andhra Pradesh', code: 'AP' },
        { name: 'Arunachal Pradesh', code: 'AR' },
        { name: 'Assam', code: 'AS' },
        { name: 'Bihar', code: 'BR' },
        { name: 'Chattisgarh', code: 'CG' },
        { name: 'Chandigarh', code: 'CH' },
        { name: 'Daman and Diu', code: 'DD' },
        { name: 'Delhi', code: 'DL' },
        { name: 'Dadra and Nagar Haveli', code: 'DN' },
        { name: 'Goa', code: 'GA' },
        { name: 'Gujarat', code: 'GJ' },
        { name: 'Himachal Pradesh', code: 'HP' },
        { name: 'Haryana', code: 'HR' },
        { name: 'Jharkhand', code: 'JH' },
        { name: 'Jammu and Kashmir', code: 'JK' },
        { name: 'Karnataka', code: 'KA' },
        { name: 'Kerala', code: 'KL' },
        { name: 'Lakshadweep', code: 'LD' },
        { name: 'Maharashtra', code: 'MH' },
        { name: 'Meghalaya', code: 'ML' },
        { name: 'Manipur', code: 'MN' },
        { name: 'Madhya Pradesh', code: 'MP' },
        { name: 'Mizoram', code: 'MZ' },
        { name: 'Nagaland', code: 'NL' },
        { name: 'Orissa', code: 'OR' },
        { name: 'Punjab', code: 'PB' },
        { name: 'Puducherry', code: 'PY' },
        { name: 'Rajasthan', code: 'RJ' },
        { name: 'Sikkim', code: 'SK' },
        { name: 'Tamil Nadu', code: 'TN' },
        { name: 'Tripura', code: 'TR' },
        { name: 'Uttaranchal', code: 'UA' },
        { name: 'Uttar Pradesh', code: 'UP' },
        { name: 'West Bengal', code: 'WB' }
      ]
    },
    { id: 101, iso2: 'ID', iso3: 'IDN', other_known_names: null, name: 'Indonesia', active: true, provinces: [] },
    { id: 102, iso2: 'IR', iso3: 'IRN', other_known_names: null, name: 'Iran', active: true, provinces: [] },
    { id: 103, iso2: 'IQ', iso3: 'IRQ', other_known_names: null, name: 'Iraq', active: true, provinces: [] },
    { id: 104, iso2: 'IE', iso3: 'IRL', other_known_names: null, name: 'Ireland', active: true, provinces: [] },
    { id: 105, iso2: 'IM', iso3: 'IMN', other_known_names: null, name: 'Isle of Man', active: true, provinces: [] },
    { id: 106, iso2: 'IL', iso3: 'ISR', other_known_names: null, name: 'Israel', active: true, provinces: [] },
    { id: 107, iso2: 'IT', iso3: 'ITA', other_known_names: null, name: 'Italy', active: true, provinces: [] },
    { id: 108, iso2: 'CI', iso3: 'CIV', other_known_names: null, name: 'Ivory Coast', active: true, provinces: [] },
    { id: 109, iso2: 'JM', iso3: 'JAM', other_known_names: null, name: 'Jamaica', active: true, provinces: [] },
    { id: 110, iso2: 'JP', iso3: 'JPN', other_known_names: null, name: 'Japan', active: true, provinces: [] },
    { id: 111, iso2: 'JE', iso3: 'JEY', other_known_names: null, name: 'Jersey', active: true, provinces: [] },
    { id: 112, iso2: 'JO', iso3: 'JOR', other_known_names: null, name: 'Jordan', active: true, provinces: [] },
    { id: 113, iso2: 'KZ', iso3: 'KAZ', other_known_names: null, name: 'Kazakhstan', active: true, provinces: [] },
    { id: 114, iso2: 'KE', iso3: 'KEN', other_known_names: null, name: 'Kenya', active: true, provinces: [] },
    { id: 115, iso2: 'KI', iso3: 'KIR', other_known_names: null, name: 'Kiribati', active: true, provinces: [] },
    {
      id: 116,
      iso2: 'KR',
      iso3: 'KOR',
      other_known_names: null,
      name: 'Korea, Republic of',
      active: true,
      provinces: []
    },
    { id: 117, iso2: 'KW', iso3: 'KWT', other_known_names: null, name: 'Kuwait', active: true, provinces: [] },
    { id: 118, iso2: 'KG', iso3: 'KGZ', other_known_names: null, name: 'Kyrgyzstan', active: true, provinces: [] },
    { id: 119, iso2: 'LA', iso3: 'LAO', other_known_names: null, name: 'Laos', active: true, provinces: [] },
    { id: 120, iso2: 'LV', iso3: 'LVA', other_known_names: null, name: 'Latvia', active: true, provinces: [] },
    { id: 121, iso2: 'LB', iso3: 'LBN', other_known_names: null, name: 'Lebanon', active: true, provinces: [] },
    { id: 122, iso2: 'LS', iso3: 'LSO', other_known_names: null, name: 'Lesotho', active: true, provinces: [] },
    { id: 123, iso2: 'LR', iso3: 'LBR', other_known_names: null, name: 'Liberia', active: true, provinces: [] },
    { id: 124, iso2: 'LY', iso3: 'LBY', other_known_names: null, name: 'Libya', active: true, provinces: [] },
    { id: 125, iso2: 'LI', iso3: 'LIE', other_known_names: null, name: 'Liechtenstein', active: true, provinces: [] },
    {
      id: 126,
      iso2: 'LT',
      iso3: 'LTU',
      other_known_names: 'Republic of Lithuania',
      name: 'Lithuania',
      active: true,
      provinces: []
    },
    { id: 127, iso2: 'LU', iso3: 'LUX', other_known_names: null, name: 'Luxembourg', active: true, provinces: [] },
    { id: 128, iso2: 'MO', iso3: 'MAC', other_known_names: null, name: 'Macao', active: true, provinces: [] },
    { id: 129, iso2: 'MK', iso3: 'MKD', other_known_names: null, name: 'Macedonia', active: true, provinces: [] },
    { id: 130, iso2: 'MG', iso3: 'MDG', other_known_names: null, name: 'Madagascar', active: true, provinces: [] },
    { id: 131, iso2: 'MW', iso3: 'MWI', other_known_names: null, name: 'Malawi', active: true, provinces: [] },
    { id: 132, iso2: 'MY', iso3: 'MYS', other_known_names: null, name: 'Malaysia', active: true, provinces: [] },
    { id: 133, iso2: 'MV', iso3: 'MDV', other_known_names: null, name: 'Maldives', active: true, provinces: [] },
    { id: 134, iso2: 'ML', iso3: 'MLI', other_known_names: null, name: 'Mali', active: true, provinces: [] },
    { id: 135, iso2: 'MT', iso3: 'MLT', other_known_names: null, name: 'Malta', active: true, provinces: [] },
    {
      id: 136,
      iso2: 'MH',
      iso3: 'MHL',
      other_known_names: null,
      name: 'Marshall Islands',
      active: true,
      provinces: []
    },
    { id: 137, iso2: 'MQ', iso3: 'MTQ', other_known_names: null, name: 'Martinique', active: true, provinces: [] },
    { id: 138, iso2: 'MR', iso3: 'MRT', other_known_names: null, name: 'Mauritania', active: true, provinces: [] },
    { id: 139, iso2: 'MU', iso3: 'MUS', other_known_names: null, name: 'Mauritius', active: true, provinces: [] },
    { id: 140, iso2: 'YT', iso3: 'MYT', other_known_names: null, name: 'Mayotte', active: true, provinces: [] },
    {
      id: 141,
      iso2: 'MX',
      iso3: 'MEX',
      other_known_names: null,
      name: 'Mexico',
      active: true,
      provinces: [
        { name: 'Aguascalientes', code: 'AG' },
        { name: 'Baja California', code: 'BC' },
        { name: 'Baja California Sur', code: 'BS' },
        { name: 'Campeche', code: 'CM' },
        { name: 'Chiapas', code: 'CS' },
        { name: 'Morelos', code: 'MO' },
        { name: 'Nayarit', code: 'NA' },
        { name: 'Nuevo León', code: 'NL' },
        { name: 'Oaxaca', code: 'OA' },
        { name: 'Puebla', code: 'PU' },
        { name: 'Chihuahua', code: 'CH' },
        { name: 'Coahuila', code: 'CO' },
        { name: 'Colima', code: 'CL' },
        { name: 'Ciudad de México', code: 'DF' },
        { name: 'Durango', code: 'DG' },
        { name: 'Guanajuato', code: 'GT' },
        { name: 'Guerrero', code: 'GR' },
        { name: 'Hidalgo', code: 'HG' },
        { name: 'Jalisco', code: 'JA' },
        { name: 'Estado de México', code: 'EM' },
        { name: 'Michoacán', code: 'MI' },
        { name: 'Querétaro', code: 'QE' },
        { name: 'Quintana Roo', code: 'QR' },
        { name: 'San Luis Potosí', code: 'SL' },
        { name: 'Sinaloa', code: 'SI' },
        { name: 'Sonora', code: 'SO' },
        { name: 'Tabasco', code: 'TB' },
        { name: 'Tamaulipas', code: 'TM' },
        { name: 'Tlaxcala', code: 'TL' },
        { name: 'Veracruz', code: 'VE' },
        { name: 'Yucatán', code: 'YU' },
        { name: 'Zacatecas', code: 'ZA' }
      ]
    },
    { id: 142, iso2: 'FM', iso3: 'FSM', other_known_names: null, name: 'Micronesia', active: true, provinces: [] },
    { id: 143, iso2: 'MD', iso3: 'MDA', other_known_names: null, name: 'Moldova', active: true, provinces: [] },
    { id: 144, iso2: 'MC', iso3: 'MCO', other_known_names: null, name: 'Monaco', active: true, provinces: [] },
    { id: 145, iso2: 'MN', iso3: 'MNG', other_known_names: null, name: 'Mongolia', active: true, provinces: [] },
    { id: 146, iso2: 'ME', iso3: 'MNE', other_known_names: null, name: 'Montenegro', active: false, provinces: [] },
    { id: 147, iso2: 'MS', iso3: 'MSR', other_known_names: null, name: 'Montserrat', active: true, provinces: [] },
    { id: 148, iso2: 'MA', iso3: 'MAR', other_known_names: null, name: 'Morocco', active: true, provinces: [] },
    { id: 149, iso2: 'MZ', iso3: 'MOZ', other_known_names: null, name: 'Mozambique', active: true, provinces: [] },
    { id: 150, iso2: 'MM', iso3: 'MMR', other_known_names: null, name: 'Myanmar', active: true, provinces: [] },
    { id: 151, iso2: 'NA', iso3: 'NAM', other_known_names: null, name: 'Namibia', active: true, provinces: [] },
    { id: 152, iso2: 'NR', iso3: 'NRU', other_known_names: null, name: 'Nauru', active: true, provinces: [] },
    { id: 153, iso2: 'NP', iso3: 'NPL', other_known_names: null, name: 'Nepal', active: true, provinces: [] },
    {
      id: 154,
      iso2: 'AN',
      iso3: 'ANT',
      other_known_names: null,
      name: 'Netherlands Antilles',
      active: true,
      provinces: []
    },
    {
      id: 155,
      iso2: 'NL',
      iso3: 'NLD',
      other_known_names: 'The Netherlands',
      name: 'Netherlands',
      active: true,
      provinces: []
    },
    { id: 156, iso2: 'NC', iso3: 'NCL', other_known_names: null, name: 'New Caledonia', active: true, provinces: [] },
    { id: 157, iso2: 'NZ', iso3: 'NZL', other_known_names: null, name: 'New Zealand', active: true, provinces: [] },
    { id: 158, iso2: 'NI', iso3: 'NIC', other_known_names: null, name: 'Nicaragua', active: true, provinces: [] },
    { id: 159, iso2: 'NE', iso3: 'NER', other_known_names: null, name: 'Niger', active: true, provinces: [] },
    { id: 160, iso2: 'NG', iso3: 'NGA', other_known_names: null, name: 'Nigeria', active: true, provinces: [] },
    { id: 161, iso2: 'NU', iso3: 'NIU', other_known_names: null, name: 'Niue', active: true, provinces: [] },
    { id: 162, iso2: 'NF', iso3: 'NFK', other_known_names: null, name: 'Norfolk Island', active: true, provinces: [] },
    { id: 163, iso2: 'KP', iso3: 'PRK', other_known_names: null, name: 'North Korea', active: true, provinces: [] },
    {
      id: 164,
      iso2: 'MP',
      iso3: 'NMP',
      other_known_names: null,
      name: 'Northern Mariana Islands',
      active: true,
      provinces: []
    },
    { id: 165, iso2: 'NO', iso3: 'NOR', other_known_names: null, name: 'Norway', active: true, provinces: [] },
    { id: 166, iso2: 'OM', iso3: 'OMN', other_known_names: null, name: 'Oman', active: true, provinces: [] },
    { id: 167, iso2: 'PK', iso3: 'PAK', other_known_names: null, name: 'Pakistan', active: true, provinces: [] },
    { id: 168, iso2: 'PW', iso3: 'PLW', other_known_names: null, name: 'Palau', active: true, provinces: [] },
    {
      id: 169,
      iso2: 'PS',
      iso3: 'PSE',
      other_known_names: null,
      name: 'Palestinian Territory',
      active: true,
      provinces: []
    },
    { id: 170, iso2: 'PA', iso3: 'PAN', other_known_names: null, name: 'Panama', active: true, provinces: [] },
    {
      id: 171,
      iso2: 'PG',
      iso3: 'PNG',
      other_known_names: null,
      name: 'Papua New Guinea',
      active: true,
      provinces: []
    },
    { id: 172, iso2: 'PY', iso3: 'PRY', other_known_names: null, name: 'Paraguay', active: true, provinces: [] },
    { id: 173, iso2: 'PE', iso3: 'PER', other_known_names: null, name: 'Peru', active: true, provinces: [] },
    { id: 174, iso2: 'PH', iso3: 'PHL', other_known_names: null, name: 'Philippines', active: true, provinces: [] },
    { id: 175, iso2: 'PN', iso3: 'PCN', other_known_names: null, name: 'Pitcairn Island', active: true, provinces: [] },
    { id: 176, iso2: 'PL', iso3: 'POL', other_known_names: null, name: 'Poland', active: true, provinces: [] },
    { id: 177, iso2: 'PT', iso3: 'PRT', other_known_names: null, name: 'Portugal', active: true, provinces: [] },
    { id: 178, iso2: 'PR', iso3: 'PRI', other_known_names: null, name: 'Puerto Rico', active: true, provinces: [] },
    { id: 179, iso2: 'QA', iso3: 'QAT', other_known_names: null, name: 'Qatar', active: true, provinces: [] },
    { id: 180, iso2: 'RE', iso3: 'REU', other_known_names: null, name: 'Réunion', active: true, provinces: [] },
    { id: 181, iso2: 'RO', iso3: 'ROU', other_known_names: null, name: 'Romania', active: true, provinces: [] },
    {
      id: 182,
      iso2: 'RU',
      iso3: 'RUS',
      other_known_names: null,
      name: 'Russian Federation',
      active: false,
      provinces: []
    },
    { id: 183, iso2: 'RW', iso3: 'RWA', other_known_names: null, name: 'Rwanda', active: true, provinces: [] },
    {
      id: 184,
      iso2: 'BL',
      iso3: 'BLM',
      other_known_names: null,
      name: 'Saint Barthélemy',
      active: false,
      provinces: []
    },
    { id: 185, iso2: 'SH', iso3: 'SHN', other_known_names: null, name: 'Saint Helena', active: true, provinces: [] },
    {
      id: 186,
      iso2: 'KN',
      iso3: 'KNA',
      other_known_names: null,
      name: 'Saint Kitts and Nevis',
      active: true,
      provinces: []
    },
    { id: 187, iso2: 'LC', iso3: 'LCA', other_known_names: null, name: 'Saint Lucia', active: true, provinces: [] },
    { id: 188, iso2: 'MF', iso3: 'MAF', other_known_names: null, name: 'Saint Martin', active: false, provinces: [] },
    {
      id: 189,
      iso2: 'PM',
      iso3: 'SPM',
      other_known_names: null,
      name: 'Saint Pierre and Miquelon',
      active: true,
      provinces: []
    },
    {
      id: 190,
      iso2: 'VC',
      iso3: 'VCT',
      other_known_names: null,
      name: 'Saint Vincent and the Grenadines',
      active: true,
      provinces: []
    },
    { id: 191, iso2: 'WS', iso3: 'WSM', other_known_names: null, name: 'Samoa', active: true, provinces: [] },
    { id: 192, iso2: 'SM', iso3: 'SMR', other_known_names: null, name: 'San Marino', active: true, provinces: [] },
    {
      id: 193,
      iso2: 'ST',
      iso3: 'STP',
      other_known_names: null,
      name: 'Sao Tome and Principe',
      active: true,
      provinces: []
    },
    { id: 194, iso2: 'SA', iso3: 'SAU', other_known_names: null, name: 'Saudi Arabia', active: true, provinces: [] },
    { id: 195, iso2: 'SN', iso3: 'SEN', other_known_names: null, name: 'Senegal', active: true, provinces: [] },
    { id: 196, iso2: 'RS', iso3: 'SRB', other_known_names: null, name: 'Serbia', active: false, provinces: [] },
    { id: 197, iso2: 'SC', iso3: 'SYC', other_known_names: null, name: 'Seychelles', active: true, provinces: [] },
    { id: 198, iso2: 'SL', iso3: 'SLE', other_known_names: null, name: 'Sierra Leone', active: true, provinces: [] },
    { id: 199, iso2: 'SG', iso3: 'SGP', other_known_names: null, name: 'Singapore', active: true, provinces: [] },
    {
      id: 200,
      iso2: 'SX',
      iso3: 'SXM',
      other_known_names: null,
      name: 'Sint Maarten (Dutch)',
      active: true,
      provinces: []
    },
    { id: 201, iso2: 'SK', iso3: 'SVK', other_known_names: null, name: 'Slovakia', active: true, provinces: [] },
    { id: 202, iso2: 'SI', iso3: 'SVN', other_known_names: null, name: 'Slovenia', active: true, provinces: [] },
    { id: 203, iso2: 'SB', iso3: 'SLB', other_known_names: null, name: 'Solomon Islands', active: true, provinces: [] },
    { id: 204, iso2: 'SO', iso3: 'SOM', other_known_names: null, name: 'Somalia', active: true, provinces: [] },
    { id: 205, iso2: 'ZA', iso3: 'ZAF', other_known_names: null, name: 'South Africa', active: true, provinces: [] },
    {
      id: 206,
      iso2: 'GS',
      iso3: 'SGS',
      other_known_names: null,
      name: 'South Georgia and the South Sandwich Islands',
      active: true,
      provinces: []
    },
    { id: 207, iso2: 'SS', iso3: 'SSD', other_known_names: null, name: 'South Sudan', active: false, provinces: [] },
    { id: 208, iso2: 'ES', iso3: 'ESP', other_known_names: null, name: 'Spain', active: true, provinces: [] },
    { id: 209, iso2: 'LK', iso3: 'LKA', other_known_names: null, name: 'Sri Lanka', active: true, provinces: [] },
    { id: 210, iso2: 'SD', iso3: 'SDN', other_known_names: null, name: 'Sudan', active: true, provinces: [] },
    { id: 211, iso2: 'SR', iso3: 'SUR', other_known_names: null, name: 'Suriname', active: true, provinces: [] },
    {
      id: 212,
      iso2: 'SJ',
      iso3: 'SJM',
      other_known_names: null,
      name: 'Svalbard and Jan Mayen Islands',
      active: true,
      provinces: []
    },
    { id: 213, iso2: 'SZ', iso3: 'SWZ', other_known_names: null, name: 'Swaziland', active: true, provinces: [] },
    { id: 214, iso2: 'SE', iso3: 'SWE', other_known_names: null, name: 'Sweden', active: true, provinces: [] },
    { id: 215, iso2: 'CH', iso3: 'CHE', other_known_names: null, name: 'Switzerland', active: true, provinces: [] },
    { id: 216, iso2: 'SY', iso3: 'SYR', other_known_names: null, name: 'Syria', active: true, provinces: [] },
    { id: 217, iso2: 'TW', iso3: 'TWN', other_known_names: null, name: 'Taiwan', active: true, provinces: [] },
    { id: 218, iso2: 'TJ', iso3: 'TJK', other_known_names: null, name: 'Tajikistan', active: true, provinces: [] },
    { id: 219, iso2: 'TZ', iso3: 'TZA', other_known_names: null, name: 'Tanzania', active: true, provinces: [] },
    { id: 220, iso2: 'TH', iso3: 'THA', other_known_names: null, name: 'Thailand', active: true, provinces: [] },
    {
      id: 221,
      iso2: 'TL',
      iso3: 'TLP',
      other_known_names: null,
      name: 'Timor-Leste (formerly East Timor)',
      active: true,
      provinces: []
    },
    { id: 222, iso2: 'TG', iso3: 'TGO', other_known_names: null, name: 'Togo', active: true, provinces: [] },
    { id: 223, iso2: 'TK', iso3: 'TKL', other_known_names: null, name: 'Tokelau', active: true, provinces: [] },
    { id: 224, iso2: 'TO', iso3: 'TON', other_known_names: null, name: 'Tonga', active: true, provinces: [] },
    {
      id: 225,
      iso2: 'TT',
      iso3: 'TTO',
      other_known_names: null,
      name: 'Trinidad and Tobago',
      active: true,
      provinces: []
    },
    { id: 226, iso2: 'TN', iso3: 'TUN', other_known_names: null, name: 'Tunisia', active: true, provinces: [] },
    { id: 227, iso2: 'TR', iso3: 'TUR', other_known_names: null, name: 'Turkey', active: true, provinces: [] },
    { id: 228, iso2: 'TM', iso3: 'TKM', other_known_names: null, name: 'Turkmenistan', active: true, provinces: [] },
    {
      id: 229,
      iso2: 'TC',
      iso3: 'TCA',
      other_known_names: null,
      name: 'Turks and Caicos Islands',
      active: true,
      provinces: []
    },
    { id: 230, iso2: 'TV', iso3: 'TUV', other_known_names: null, name: 'Tuvalu', active: true, provinces: [] },
    { id: 231, iso2: 'UG', iso3: 'UGA', other_known_names: null, name: 'Uganda', active: true, provinces: [] },
    { id: 232, iso2: 'UA', iso3: 'UKR', other_known_names: null, name: 'Ukraine', active: true, provinces: [] },
    {
      id: 233,
      iso2: 'AE',
      iso3: 'ARE',
      other_known_names: null,
      name: 'United Arab Emirates',
      active: true,
      provinces: []
    },
    {
      id: 234,
      iso2: 'GB',
      iso3: 'GBR',
      other_known_names: 'UK, Great Britain, England',
      name: 'United Kingdom',
      active: true,
      provinces: []
    },
    {
      id: 235,
      iso2: 'UM',
      iso3: 'UMI',
      other_known_names: null,
      name: 'United States Minor Outlying Islands',
      active: true,
      provinces: []
    },
    {
      id: 236,
      iso2: 'VI',
      iso3: 'VIR',
      other_known_names: null,
      name: 'United States Virgin Islands',
      active: true,
      provinces: []
    },
    {
      id: 237,
      iso2: 'US',
      iso3: 'USA',
      other_known_names: 'United States of America',
      name: 'United States',
      active: true,
      provinces: [
        { name: 'Alabama', code: 'AL' },
        { name: 'Alaska', code: 'AK' },
        { name: 'Arizona', code: 'AZ' },
        { name: 'Arkansas', code: 'AR' },
        { name: 'California', code: 'CA' },
        { name: 'Colorado', code: 'CO' },
        { name: 'Connecticut', code: 'CT' },
        { name: 'Delaware', code: 'DE' },
        { name: 'District of Columbia', code: 'DC' },
        { name: 'Florida', code: 'FL' },
        { name: 'Georgia', code: 'GA' },
        { name: 'Hawaii', code: 'HI' },
        { name: 'Idaho', code: 'ID' },
        { name: 'Illinois', code: 'IL' },
        { name: 'Montana', code: 'MT' },
        { name: 'Nebraska', code: 'NE' },
        { name: 'Nevada', code: 'NV' },
        { name: 'New Hampshire', code: 'NH' },
        { name: 'New Jersey', code: 'NJ' },
        { name: 'New Mexico', code: 'NM' },
        { name: 'New York', code: 'NY' },
        { name: 'North Carolina', code: 'NC' },
        { name: 'North Dakota', code: 'ND' },
        { name: 'Ohio', code: 'OH' },
        { name: 'Oklahoma', code: 'OK' },
        { name: 'Oregon', code: 'OR' },
        { name: 'Pennsylvania', code: 'PA' },
        { name: 'Rhode Island', code: 'RI' },
        { name: 'Indiana', code: 'IN' },
        { name: 'Iowa', code: 'IA' },
        { name: 'Kansas', code: 'KS' },
        { name: 'Kentucky', code: 'KY' },
        { name: 'Louisiana', code: 'LA' },
        { name: 'Maine', code: 'ME' },
        { name: 'Maryland', code: 'MD' },
        { name: 'Massachusetts', code: 'MA' },
        { name: 'Michigan', code: 'MI' },
        { name: 'Minnesota', code: 'MN' },
        { name: 'Mississippi', code: 'MS' },
        { name: 'Missouri', code: 'MO' },
        { name: 'South Carolina', code: 'SC' },
        { name: 'South Dakota', code: 'SD' },
        { name: 'Tennessee', code: 'TN' },
        { name: 'Texas', code: 'TX' },
        { name: 'Utah', code: 'UT' },
        { name: 'Vermont', code: 'VT' },
        { name: 'Virginia', code: 'VA' },
        { name: 'Washington State', code: 'WA' },
        { name: 'West Virginia', code: 'WV' },
        { name: 'Wisconsin', code: 'WI' },
        { name: 'Wyoming', code: 'WY' },
        { name: 'Puerto Rico', code: 'PR' }
      ]
    },
    { id: 238, iso2: 'UY', iso3: 'URY', other_known_names: null, name: 'Uruguay', active: true, provinces: [] },
    { id: 239, iso2: 'UZ', iso3: 'UZB', other_known_names: null, name: 'Uzbekistan', active: true, provinces: [] },
    { id: 240, iso2: 'VU', iso3: 'VUT', other_known_names: null, name: 'Vanuatu', active: true, provinces: [] },
    { id: 241, iso2: 'VE', iso3: 'VEN', other_known_names: null, name: 'Venezuela', active: true, provinces: [] },
    { id: 242, iso2: 'VN', iso3: 'VNM', other_known_names: null, name: 'Vietnam', active: true, provinces: [] },
    {
      id: 243,
      iso2: 'WF',
      iso3: 'WLF',
      other_known_names: null,
      name: 'Wallis and Futuna Islands',
      active: true,
      provinces: []
    },
    { id: 244, iso2: 'EH', iso3: 'ESH', other_known_names: null, name: 'Western Sahara', active: true, provinces: [] },
    { id: 245, iso2: 'YE', iso3: 'YEM', other_known_names: null, name: 'Yemen', active: false, provinces: [] },
    { id: 246, iso2: 'ZM', iso3: 'ZMB', other_known_names: null, name: 'Zambia', active: true, provinces: [] },
    { id: 247, iso2: 'ZW', iso3: 'ZWE', other_known_names: null, name: 'Zimbabwe', active: true, provinces: [] },
    { id: 248, iso2: 'BV', iso3: '', other_known_names: null, name: 'Bouvet Island', active: true, provinces: [] },
    {
      id: 249,
      iso2: 'HM',
      iso3: '',
      other_known_names: null,
      name: 'Heard Island and McDonald Islands',
      active: true,
      provinces: []
    }
  ]
};

const sizes = {
  count: 15,
  next: null,
  previous: null,
  results: [
    {
      id: 22,
      name: "6-12M",
      category: "BABY",
      modified_on: "2021-07-15T19:26:36.260250Z",
      sort_order: 1,
    },
    {
      id: 21,
      name: "NB",
      category: "BABY",
      modified_on: "2021-07-15T18:32:17.890273Z",
      sort_order: 1,
    },
    {
      id: 9,
      name: "One Size",
      category: "Generic",
      modified_on: "2019-09-11T04:24:42.848470Z",
      sort_order: 1,
    },
    {
      id: 10,
      name: "XXS",
      category: "Apparel",
      modified_on: "2020-10-22T22:37:50.970003Z",
      sort_order: 1,
    },
    {
      id: 23,
      name: "3-6M",
      category: "BABY",
      modified_on: "2021-07-15T20:57:44.427687Z",
      sort_order: 1,
    },
    {
      id: 1,
      name: "XS",
      category: "Apparel",
      modified_on: "2020-12-14T20:29:45.095071Z",
      sort_order: 2,
    },
    {
      id: 2,
      name: "S",
      category: "Apparel",
      modified_on: "2020-10-22T22:38:10.862558Z",
      sort_order: 3,
    },
    {
      id: 3,
      name: "M",
      category: "Apparel",
      modified_on: "2020-10-22T22:38:19.169442Z",
      sort_order: 4,
    },
    {
      id: 4,
      name: "L",
      category: "Apparel",
      modified_on: "2020-10-22T22:38:26.821228Z",
      sort_order: 5,
    },
    {
      id: 5,
      name: "XL",
      category: "Apparel",
      modified_on: "2020-12-14T20:29:11.921887Z",
      sort_order: 6,
    },
    {
      id: 6,
      name: "2XL",
      category: "Apparel",
      modified_on: "2020-10-22T22:44:16.042215Z",
      sort_order: 7,
    },
    {
      id: 7,
      name: "3XL",
      category: "Apparel",
      modified_on: "2020-10-22T22:47:14.390559Z",
      sort_order: 8,
    },
    {
      id: 8,
      name: "4XL",
      category: "Apparel",
      modified_on: "2020-07-27T16:23:49.258951Z",
      sort_order: 9,
    },
    {
      id: 19,
      name: "5XL",
      category: "Apparel",
      modified_on: "2021-08-19T15:36:57.497198Z",
      sort_order: 10,
    },
    {
      id: 20,
      name: "6XL",
      category: "Apparel",
      modified_on: "2021-08-19T15:37:51.070272Z",
      sort_order: 11,
    },
  ],
};



export { shipmentStatus, productStatus, redactedText, countries, sizes };